### ISSUE TITLE
DrmSession called from wrong thread!

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#177]
### Description of the problem

When playing a DRM content, the logcat receive a large amont of warning. As we know Exoplayer, they will soon or later make the warning crashes. So it would be nice to fixe it.

### Relevant stack trace or log output

```shell
DefaultDrmSession accessed on the wrong thread.
                                                                                                    Current thread: ExoPlayer:Playback
                                                                                                    Expected thread: main
                                                                                                      java.lang.IllegalStateException
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.verifyPlaybackThread(DefaultDrmSession.java:584)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.getState(DefaultDrmSession.java:261)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.mayReadSample(SampleQueue.java:947)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.isReady(SampleQueue.java:397)
                                                                                                          at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.isReady(ChunkSampleStream.java:367)
                                                                                                          at androidx.media3.exoplayer.BaseRenderer.isSourceReady(BaseRenderer.java:508)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.isReady(MediaCodecRenderer.java:1693)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.isReady(MediaCodecVideoRenderer.java:585)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1057)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                          at android.os.Looper.loop(Looper.java:313)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Reproducibility

Always

### Steps to reproduce

Open the demo an start playing a drm content with the _logcat_ open.

### Library version

0.4.1

### Operating system

all

### Is there an existing issue for this?

- [X] I have searched existing issues and found no similar bug report.

**Comment by StaehliJ** [comment]
On 0.4.0 no warning in the logcat, it started with media3 1.1.0 update
